Style/Copyright:
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: false

# Enabled by default
Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

# TODO: Would be nice to use this but man does it fuck with Align-Hash
Style/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: false

Lint/IneffectiveAccessModifier:
  Description: >-
                 Checks for attempts to use `private` or `protected` to set
                 the visibility of a class method, which does not work.
  Enabled: false

Style/InlineComment:
  Description: 'Avoid inline comments.'
  Enabled: false

Style/MissingElse:
  Description: >-
                Require if/case expressions to have an else branches.
                If enabled, it is recommended that
                Style/UnlessElse and Style/EmptyElse be enabled.
                This will conflict with Style/EmptyElse if
                Style/EmptyElse is configured to style "both"
  Enabled: false
  EnforcedStyle: both
  SupportedStyles:
    # if - warn when an if expression is missing an else branch
    # case - warn when a case expression is misisng an else branch
    # both - warn when an if or case expression is missing an else branch
    - if
    - case
    - both

Style/MultilineArrayBraceLayout:
  Description: >-
                 Checks that the closing brace in an array literal is
                 symmetrical with respect to the opening brace and the
                 array elements.
  Enabled: false

Style/MultilineAssignmentLayout:
  Description: 'Check for a newline after the assignment operator in multi-line assignments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#indent-conditional-assignment'
  Enabled: false

Style/MultilineHashBraceLayout:
  Description: >-
                 Checks that the closing brace in a hash literal is
                 symmetrical with respect to the opening brace and the
                 hash elements.
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Description: >-
                 Checks that the closing brace in a method call is
                 symmetrical with respect to the opening brace and the
                 method arguments.
  Enabled: false

Style/MultilineMethodDefinitionBraceLayout:
  Description: >-
                 Checks that the closing brace in a method definition is
                 symmetrical with respect to the opening brace and the
                 method parameters.
  Enabled: false

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-i'
  Enabled: false

# Enabled by default, but it messes with stuff
Style/TrailingUnderscoreVariable:
  Description: >-
                 Checks for the usage of unneeded trailing underscores at the
                 end of parallel variable assignment.
  Enabled: false

# Too rails specific
Rails/Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

# Enabled by default, but super chatty and it's not useful with activesupport
Rails/TimeZone:
  Description: 'Checks the correct usage of time zone aware methods.'
  StyleGuide: 'https://github.com/bbatsov/rails-style-guide#time'
  Reference: 'http://danilenko.org/2012/7/6/rails_timezones'
  Enabled: false

Lint/LiteralInInterpolation:
  Description: 'Avoid interpolating literals in strings'
  AutoCorrect: false
  Enabled: false

Lint/UselessAccessModifier:
  Description: 'Checks for useless access modifiers.'
  Enabled: false
